// SPDX-License-Identifier: GPL-2.0
//
// Turns the build-time knobs handed over by the Makefile into Rust constants.
// Everything the init needs to know about the device layout is therefore
// editable from the command line (`make USERDATA_PART=...`) instead of having
// to poke at the source.  Also fingerprints ../firmware so that init can tell
// whether the copy it left in the distro is still the one bundled here.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// (environment variable, generated constant, default value)
const STRINGS: &[(&str, &str, &str)] = &[
    ("ARIES_USERDATA_PART", "USERDATA_PART", "/dev/mmcblk0p23"),
    ("ARIES_DISTRO_SUBDIR", "DISTRO_SUBDIR", "rootfs"),
    ("ARIES_ROOTFS_FSTYPE", "ROOTFS_FSTYPE", "ext4"),
];

/// (environment variable, generated constant, default value)
const NUMBERS: &[(&str, &str, i64)] = &[("ARIES_SHUTDOWN_DELAY", "SHUTDOWN_DELAY", 15)];

const FNV_BASIS: u64 = 0xcbf29ce484222325;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    // A firmware edit has to move FIRMWARE_STAMP, so cargo must re-run us.
    println!("cargo:rerun-if-changed=../firmware");

    let mut out = String::from("// Generated by build.rs - do not edit.\n");

    for (var, name, default) in STRINGS {
        println!("cargo:rerun-if-env-changed={var}");
        let value = env::var(var).ok().filter(|v| !v.is_empty());
        let value = value.as_deref().unwrap_or(default);
        // `{:?}` produces a properly escaped Rust string literal.
        out.push_str(&format!("pub const {name}: &str = {value:?};\n"));
    }

    for (var, name, default) in NUMBERS {
        println!("cargo:rerun-if-env-changed={var}");
        let value = env::var(var)
            .ok()
            .and_then(|v| v.parse::<i64>().ok())
            .unwrap_or(*default);
        out.push_str(&format!("pub const {name}: i64 = {value};\n"));
    }

    let firmware = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("init/ has a parent")
        .join("firmware");
    let stamp = firmware_stamp(&firmware);
    out.push_str(&format!("pub const FIRMWARE_STAMP: &str = {stamp:?};\n"));

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("config.rs");
    fs::write(dest, out).expect("write config.rs");
}

/// FNV-1a 64: a dozen lines instead of a hash crate, for a value that only has
/// to change whenever firmware/ does.
struct Fnv(u64);

impl Fnv {
    const PRIME: u64 = 0x100000001b3;

    fn write(&mut self, bytes: &[u8]) {
        for b in bytes {
            self.0 = (self.0 ^ u64::from(*b)).wrapping_mul(Self::PRIME);
        }
    }
}

/// Identity of the tree that becomes /lib/firmware in the initramfs.  init
/// leaves it next to the copy it makes in the distro, which is what lets the
/// next boot skip verifying the ~8 MiB file by file.
fn firmware_stamp(dir: &Path) -> String {
    let dir = fs::canonicalize(dir).unwrap_or_else(|_| dir.to_path_buf());
    let mut files = Vec::new();
    collect_files(&dir, &mut files);
    files.sort();

    let mut hash = Fnv(FNV_BASIS);
    for path in files {
        let rel = path.strip_prefix(&dir).unwrap_or(&path);
        // Name, kind, then bytes: a rename, a symlink swap or a single flipped
        // bit anywhere under firmware/ all move the stamp.
        hash.write(rel.to_string_lossy().as_bytes());
        hash.write(b"\0");
        if let Ok(content) = fs::read(&path) {
            hash.write(b"f");
            hash.write(&content);
        } else if let Ok(target) = fs::read_link(&path) {
            hash.write(b"l");
            hash.write(target.to_string_lossy().as_bytes());
        } else {
            hash.write(b"?");
        }
        hash.write(b"\0");
    }
    format!("{:016x}", hash.0)
}

/// Every non-directory below `dir`, in no particular order.
fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if entry.file_type().is_ok_and(|ty| ty.is_dir()) {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}
