// SPDX-License-Identifier: GPL-2.0
//
// Minimal initramfs /init for the Xiaomi Mi 2 (aries, APQ8064) on mainline
// Linux, booted through lk2nd.  Mounts the pseudo-filesystems, waits for
// userdata, copies the bundled firmware over, then switch_roots into
// <userdata>/<DISTRO_SUBDIR> and execs the distro init.  On any failure the
// log is parked on the userdata partition and the device powers off.

// Must precede the `mod` declarations so the child modules can see it.
macro_rules! log {
    ($($arg:tt)*) => {
        crate::logger::line(format_args!($($arg)*))
    };
}

mod logger;
mod sys;

use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::os::unix::process::CommandExt;
use std::path::{Component, Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::OnceLock;
use std::time::{Duration, Instant};

// Generated by build.rs from the values handed over by the Makefile.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

const FIRMWARE_SRC: &str = "/lib/firmware";
/// Left in <rootfs>/lib/firmware once the bundled tree is complete.  Its
/// content is FIRMWARE_STAMP, which build.rs derives from firmware/, so a match
/// proves the tree below is already ours.
const FIRMWARE_STAMP_FILE: &str = ".aries-firmware-stamp";
const NEWROOT: &str = "/newroot";
// LM3530 boots at brightness 0; set something so the bring-up log is readable.
const BACKLIGHT: &str = "/sys/class/leds/lcd-backlight/brightness";
const INIT_CANDIDATES: &[&str] =
    &["sbin/init", "init", "usr/sbin/init", "bin/init", "usr/bin/init"];

const WAIT_PART: Duration = Duration::from_secs(15);
const WAIT_BACKLIGHT: Duration = Duration::from_secs(2);
const MAX_SYMLINKS: usize = 16;
const KMSG_LIMIT: usize = 2 * 1024 * 1024; // log_buf_len=2M
const O_NONBLOCK: i32 = 0o4000;

static IN_FATAL: AtomicBool = AtomicBool::new(false);
static SWITCHED_ROOT: AtomicBool = AtomicBool::new(false);

fn main() {
    std::panic::set_hook(Box::new(|info| {
        // Funnel panics through the same save-log-and-power-off path as errors.
        logger::line(format_args!("PANIC {info}"));
        fatal("panic");
    }));

    if let Err(e) = early_setup() {
        fatal(&format!("early setup: {e}"));
    }
    if let Err(e) = boot() {
        fatal(&e);
    }
    fatal("init returned without handing over to the root filesystem");
}

fn early_setup() -> Result<(), String> {
    for dir in ["/dev", "/proc", "/sys", "/tmp", "/run", "/mnt", NEWROOT] {
        mkdir_p(Path::new(dir))?;
    }

    mount_fs("proc", "/proc", "proc", sys::MS_NOSUID | sys::MS_NODEV | sys::MS_NOEXEC, None)?;
    mount_fs("sysfs", "/sys", "sysfs", sys::MS_NOSUID | sys::MS_NODEV | sys::MS_NOEXEC, None)?;

    // CONFIG_DEVTMPFS_MOUNT=y normally did this already.
    if !is_mounted("/dev") {
        mount_fs(
            "devtmpfs",
            "/dev",
            "devtmpfs",
            sys::MS_NOSUID | sys::MS_STRICTATIME,
            Some("mode=0755"),
        )?;
    }

    logger::attach_kmsg(OpenOptions::new().write(true).open("/dev/kmsg").ok());

    log!("------- aries initramfs -------");
    log!("userdata {USERDATA_PART} ({ROOTFS_FSTYPE}) -> /{DISTRO_SUBDIR}");

    if let Err(e) = sys::sethostname("aries") {
        log!("WARN sethostname: {e}");
    }
    Ok(())
}

fn boot() -> Result<(), String> {
    bring_up_backlight();

    log!("waiting for {USERDATA_PART}");
    wait_for(USERDATA_PART, WAIT_PART)?;

    mount_fs(USERDATA_PART, NEWROOT, ROOTFS_FSTYPE, sys::MS_NOATIME, None)?;
    log!("mounted {USERDATA_PART} on {NEWROOT}");

    let distro = PathBuf::from(format!("{NEWROOT}/{DISTRO_SUBDIR}"));
    if !distro.is_dir() {
        return Err(format!(
            "{} is not a directory - the distro has to live in <userdata>/{DISTRO_SUBDIR}",
            distro.display()
        ));
    }

    let init_rel = find_init(&distro).ok_or_else(|| {
        format!("no executable init below {} (tried {:?})", distro.display(), INIT_CANDIDATES)
    })?;
    log!("distro root {} (init: /{init_rel})", distro.display());

    install_firmware(&distro);

    pre_mount(&distro)?;

    hand_over(&distro, init_rel)
}

#[derive(Default)]
struct CopyStats {
    files: u64,
    copied: u64,
    bytes: u64,
    errors: u64,
}

fn install_firmware(distro: &Path) {
    let src = Path::new(FIRMWARE_SRC);
    if !src.is_dir() {
        log!("WARN {FIRMWARE_SRC} is missing from the initramfs");
        return;
    }

    let dst = distro.join("lib/firmware");
    let stamp = dst.join(FIRMWARE_STAMP_FILE);

    // The bundled firmware only ever changes with this binary, so a matching
    // stamp proves the whole tree is ours and saves reading ~8 MiB back off the
    // eMMC on every boot.
    if fs::read_to_string(&stamp).is_ok_and(|s| s == FIRMWARE_STAMP) {
        log!("firmware: {} already matches this initramfs", dst.display());
        return;
    }

    let mut stats = CopyStats::default();
    copy_tree(src, &dst, &mut stats);

    let up_to_date = stats.files.saturating_sub(stats.copied + stats.errors);
    log!(
        "firmware: {} files -> {} ({} written, {} KiB, {} already up to date)",
        stats.files,
        dst.display(),
        stats.copied,
        stats.bytes / 1024,
        up_to_date
    );
    // Only a complete tree gets stamped; a partial one has to be retried, so
    // the next boot must not be able to mistake it for a finished one.
    if stats.errors > 0 {
        log!("WARN firmware: {} entries could not be copied", stats.errors);
    } else if let Err(e) = fs::write(&stamp, FIRMWARE_STAMP) {
        log!("WARN firmware: could not write {}: {e}", stamp.display());
    }
}

/// True when `to` already holds the same bytes as `from`; avoids rewriting
/// ~8 MiB of firmware to the eMMC on every boot.
fn same_content(from: &Path, to: &Path) -> bool {
    let (Ok(mut left), Ok(mut right)) = (File::open(from), File::open(to)) else {
        return false;
    };

    let (Ok(left_meta), Ok(right_meta)) = (left.metadata(), right.metadata()) else {
        return false;
    };
    // A stale directory at the destination opens fine but never matches.
    if !left_meta.is_file() || !right_meta.is_file() || left_meta.len() != right_meta.len() {
        return false;
    }

    let mut left_buf = [0u8; 64 * 1024];
    let mut right_buf = [0u8; 64 * 1024];
    loop {
        let read = match left.read(&mut left_buf) {
            Ok(0) => return true,
            Ok(n) => n,
            Err(_) => return false,
        };
        if right.read_exact(&mut right_buf[..read]).is_err() {
            return false;
        }
        if left_buf[..read] != right_buf[..read] {
            return false;
        }
    }
}

fn pre_mount(distro: &Path) -> Result<(), String> {
    // `dev` must be a mount point before `dev/pts` can live inside it.
    let table: &[(&str, &str, usize, Option<&str>)] = &[
        ("dev", "devtmpfs", sys::MS_NOSUID | sys::MS_STRICTATIME, Some("mode=0755")),
        ("dev/pts", "devpts", sys::MS_NOSUID | sys::MS_NOEXEC, None),
        ("proc", "proc", sys::MS_NOSUID | sys::MS_NODEV | sys::MS_NOEXEC, None),
        ("sys", "sysfs", sys::MS_NOSUID | sys::MS_NODEV | sys::MS_NOEXEC, None),
        ("tmp", "tmpfs", sys::MS_NOSUID | sys::MS_NODEV, Some("mode=1777")),
        ("run", "tmpfs", sys::MS_NOSUID | sys::MS_NODEV, Some("mode=0755")),
    ];

    for (rel, fstype, flags, data) in table {
        let target = distro.join(rel);
        let target = target.to_str().ok_or("non-UTF-8 path in the distro root")?;
        mkdir_p(Path::new(target))?;
        // A distro that manages these itself must not fail the boot.
        if let Err(e) = mount_fs(fstype, target, fstype, *flags, *data) {
            log!("WARN mount {fstype} on {target}: {e}");
        }
    }
    Ok(())
}

fn hand_over(distro: &Path, init_rel: &str) -> Result<(), String> {
    let distro_str = distro.to_str().ok_or("non-UTF-8 distro root")?;

    // switch_root needs the distro as a *mount point*: bind it onto itself
    // first, MS_REC drags the /dev, /proc, ... mounts along.
    sys::mount(Some(distro_str), distro_str, None, sys::MS_BIND | sys::MS_REC, None)
        .map_err(|e| format!("bind mount {distro_str} onto itself: {e}"))?;

    std::env::set_current_dir(distro).map_err(|e| format!("chdir {}: {e}", distro.display()))?;

    // Landing zone for the old root, wanted by both branches.
    mkdir_p(Path::new("mnt"))?;

    // pivot_root lets us detach the old root afterwards, releasing the ramfs
    // pages the unpacked initramfs pins; MS_MOVE would pin them for good.
    match sys::pivot_root(".", "mnt") {
        Ok(()) => {
            std::env::set_current_dir("/").map_err(|e| format!("chdir /: {e}"))?;
            if let Err(e) = sys::umount2("/mnt", sys::MNT_DETACH) {
                log!("WARN detaching the old root: {e}");
            }
            log!("switch_root: pivot_root done, initramfs released");
        }
        Err(e) => {
            log!("pivot_root failed ({e}), falling back to MS_MOVE");
            sys::mount(Some("."), "/", None, sys::MS_MOVE, None)
                .map_err(|e| format!("MS_MOVE switch_root: {e}"))?;
            sys::chroot(".").map_err(|e| format!("chroot .: {e}"))?;
            log!("switch_root: MS_MOVE done (old initramfs stays hidden under /)");
        }
    }

    SWITCHED_ROOT.store(true, Ordering::SeqCst);
    std::env::set_current_dir("/").map_err(|e| format!("chdir /: {e}"))?;
    sys::sync_all();

    let init = format!("/{init_rel}");
    log!("starting {init}");
    let err = Command::new(&init).exec();
    Err(format!("exec {init}: {err}"))
}

fn fatal(reason: &str) -> ! {
    if IN_FATAL.swap(true, Ordering::SeqCst) {
        // Re-entered (e.g. a panic inside the fatal path): try power off once
        // more, then abort so the kernel panic / watchdog takes over.
        let _ = sys::power_off();
        std::process::abort();
    }

    log!("FATAL: {reason}");
    log!("===============================================================");

    // One write, placed before the countdown so a long press during the wait
    // cannot lose it.  Nothing is logged while counting down, and the ring
    // buffer is snapshotted once, so a second save would just rewrite the same
    // ~2 MiB byte for byte.
    let saved = save_log();
    sys::sync_all();

    if SHUTDOWN_DELAY > 0 {
        countdown(SHUTDOWN_DELAY);
    }
    match saved {
        Some(path) => log!("log saved to {path}"),
        None => log!("could not write the log to the userdata partition"),
    }

    log!("powering off");
    if let Err(e) = sys::power_off() {
        log!("power off failed: {e}");
    }
    park_forever()
}

fn park_forever() -> ! {
    loop {
        std::thread::sleep(Duration::from_secs(60));
    }
}

/// Redraw "powering off in Ns" in place on the console every second; only the
/// initial line reaches the log.
fn countdown(seconds: i64) {
    log!("powering off in {seconds}s");
    let prefix = logger::PREFIX;
    let mut out = std::io::stdout().lock();
    for left in (1..=seconds).rev() {
        let _ = write!(out, "\r{prefix}: powering off in {left:>2}s ");
        let _ = out.flush();
        std::thread::sleep(Duration::from_secs(1));
    }
    let _ = write!(out, "\r");
    let _ = out.flush();
}

/// Dump our log plus the kernel ring buffer to the userdata partition.
fn save_log() -> Option<String> {
    let mut saved = None;
    for path in log_targets() {
        let path = Path::new(&path);
        if let Some(parent) = path.parent() {
            if fs::create_dir_all(parent).is_err() {
                continue;
            }
        }
        if write_log_to(path) && saved.is_none() {
            saved = Some(path.display().to_string());
        }
    }
    saved
}

/// The three parts are written straight through instead of being concatenated
/// first: the ring buffer alone is up to KMSG_LIMIT, and assembling it into a
/// second buffer would copy those 2 MiB for nothing.
fn write_log_to(path: &Path) -> bool {
    let Ok(mut file) = File::create(path) else {
        return false;
    };
    let ours = logger::snapshot();
    let parts: [&[u8]; 3] = [&ours, b"\n===== kernel ring buffer =====\n", kmsg_snapshot()];
    parts.iter().all(|part| file.write_all(part).is_ok())
}

/// Log destinations, best first; each is checked to really live on userdata
/// (create_dir_all on the initramfs tmpfs would silently fake one).
fn log_targets() -> Vec<String> {
    let mut targets = Vec::new();

    if SWITCHED_ROOT.load(Ordering::SeqCst) {
        targets.push("/initramfs-boot.log".to_string());
        if Path::new("/var/log").is_dir() {
            targets.push("/var/log/initramfs-boot.log".to_string());
        }
        return targets;
    }

    if is_mounted(NEWROOT) {
        targets.push(format!("{NEWROOT}/initramfs-boot.log"));
        if Path::new(&format!("{NEWROOT}/{DISTRO_SUBDIR}")).is_dir() {
            targets.push(format!("{NEWROOT}/{DISTRO_SUBDIR}/var/log/initramfs-boot.log"));
        }
    }
    targets
}

/// Kernel ring buffer, read once and cached (re-reading can return less as
/// the buffer wraps).
fn kmsg_snapshot() -> &'static [u8] {
    static SNAPSHOT: OnceLock<Vec<u8>> = OnceLock::new();
    SNAPSHOT.get_or_init(read_kmsg)
}

/// Non-blocking, so a drained buffer gives EAGAIN instead of parking PID 1.
fn read_kmsg() -> Vec<u8> {
    let Ok(mut file) = OpenOptions::new()
        .read(true)
        .custom_flags(O_NONBLOCK)
        .open("/dev/kmsg")
    else {
        return Vec::new();
    };

    let mut out = Vec::with_capacity(64 * 1024);
    let mut buf = [0u8; 8192];
    while out.len() < KMSG_LIMIT {
        // EOF, EAGAIN or a real error all mean stop.
        match file.read(&mut buf) {
            Ok(0) | Err(_) => break,
            // The kernel hands out one record per read, so trim the tail rather
            // than letting the last record push past the cap.
            Ok(n) => out.extend_from_slice(&buf[..n.min(KMSG_LIMIT - out.len())]),
        }
    }
    out
}

fn bring_up_backlight() {
    if Path::new(BACKLIGHT).exists() {
        set_backlight();
        return;
    }
    // Driver may still be probing: race it against the userdata wait on a
    // helper thread instead of blocking the critical path.  Never joined -
    // exec reaps it.  If the driver only appears after the switch, the distro
    // owns the backlight anyway.
    std::thread::spawn(|| {
        let deadline = Instant::now() + WAIT_BACKLIGHT;
        while !Path::new(BACKLIGHT).exists() {
            if Instant::now() >= deadline {
                log!("backlight: {BACKLIGHT} not present, leaving it alone");
                return;
            }
            std::thread::sleep(Duration::from_millis(100));
        }
        set_backlight();
    });
}

fn set_backlight() {
    match fs::write(BACKLIGHT, b"127\n") {
        Ok(()) => log!("backlight: brightness 127"),
        Err(e) => log!("WARN backlight: {e}"),
    }
}

fn mount_fs(
    source: &str,
    target: &str,
    fstype: &str,
    flags: usize,
    data: Option<&str>,
) -> Result<(), String> {
    sys::mount(Some(source), target, Some(fstype), flags, data)
        .map_err(|e| format!("mount {source} on {target} ({fstype}): {e}"))
}

fn mkdir_p(path: &Path) -> Result<(), String> {
    fs::create_dir_all(path).map_err(|e| format!("mkdir -p {}: {e}", path.display()))
}

fn is_mounted(path: &str) -> bool {
    fs::read_to_string("/proc/self/mounts")
        .map(|table| {
            table
                .lines()
                .any(|l| l.split_whitespace().nth(1) == Some(path))
        })
        .unwrap_or(false)
}

fn wait_for(path: &str, timeout: Duration) -> Result<(), String> {
    if Path::new(path).exists() {
        return Ok(());
    }
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(50));
        if Path::new(path).exists() {
            return Ok(());
        }
    }
    Err(format!("{path} did not show up within {timeout:?}"))
}

fn is_executable(path: &Path) -> bool {
    fs::metadata(path)
        .map(|m| m.is_file() && m.permissions().mode() & 0o111 != 0)
        .unwrap_or(false)
}

fn find_init(distro: &Path) -> Option<&'static str> {
    INIT_CANDIDATES
        .iter()
        .copied()
        .find(|rel| resolve_in_root(distro, rel).is_some_and(|path| is_executable(&path)))
}

/// Collapse `.` and `..` lexically; None if the path would escape the root.
fn normalize(path: &Path) -> Option<PathBuf> {
    let mut out = PathBuf::from("/");
    for comp in path.components() {
        match comp {
            Component::Normal(name) => out.push(name),
            Component::CurDir | Component::RootDir => {}
            Component::ParentDir => {
                if out.as_os_str() == "/" {
                    return None;
                }
                out.pop();
            }
            _ => return None,
        }
    }
    Some(out)
}

/// Resolve a path inside the distro to a host-side path.  `/sbin/init` is
/// usually a symlink to an absolute target (`/bin/busybox`) that plain path
/// arithmetic would resolve against the initramfs, so walk the chain by hand
/// and treat absolute targets as relative to `root`.
fn resolve_in_root(root: &Path, rel: &str) -> Option<PathBuf> {
    let mut path = PathBuf::from(format!("/{rel}"));

    for _ in 0..MAX_SYMLINKS {
        let clean = normalize(&path)?;
        let host = root.join(clean.strip_prefix("/").unwrap_or(&clean));
        if !fs::symlink_metadata(&host).ok()?.file_type().is_symlink() {
            return Some(host);
        }

        let target = fs::read_link(&host).ok()?;
        path = if target.is_absolute() {
            target
        } else {
            path.parent().unwrap_or(Path::new("/")).join(target)
        };
    }

    None
}

fn copy_tree(src: &Path, dst: &Path, stats: &mut CopyStats) {
    if let Err(e) = fs::create_dir_all(dst) {
        log!("WARN   mkdir {}: {e}", dst.display());
        stats.errors += 1;
        return;
    }

    let entries = match fs::read_dir(src) {
        Ok(entries) => entries,
        Err(e) => {
            log!("WARN   opendir {}: {e}", src.display());
            stats.errors += 1;
            return;
        }
    };

    for entry in entries.flatten() {
        let from = entry.path();
        let to = dst.join(entry.file_name());
        match entry.file_type() {
            Ok(ty) if ty.is_dir() => copy_tree(&from, &to, stats),
            Ok(ty) if ty.is_file() => {
                stats.files += 1;
                if same_content(&from, &to) {
                    continue;
                }
                // fs::copy already carries the permission bits over.
                match fs::copy(&from, &to) {
                    Ok(n) => {
                        stats.copied += 1;
                        stats.bytes += n;
                    }
                    Err(e) => {
                        log!("WARN   copy {}: {e}", from.display());
                        stats.errors += 1;
                    }
                }
            }
            Ok(ty) if ty.is_symlink() => {
                stats.files += 1;
                match fs::read_link(&from) {
                    Ok(target) => {
                        if fs::read_link(&to).is_ok_and(|t| t == target) {
                            continue;
                        }
                        let _ = fs::remove_file(&to);
                        match std::os::unix::fs::symlink(&target, &to) {
                            Ok(()) => stats.copied += 1,
                            Err(e) => {
                                log!("WARN   symlink {}: {e}", from.display());
                                stats.errors += 1;
                            }
                        }
                    }
                    Err(e) => {
                        log!("WARN   readlink {}: {e}", from.display());
                        stats.errors += 1;
                    }
                }
            }
            _ => {}
        }
    }
}
